In [4]:
#4 데이터 다루기

from sklearn.preprocessing import MinMaxScaler
import numpy as np

X_train = np.array([[1], [23], [15], [22], [7]])
X_test = np.array([[6], [15], [30], [2], [21]])

scaler = MinMaxScaler(feature_range=(-1, 1))
X_train_std = scaler.fit_transform(X_train)
X_test_sid = scaler.transform(X_test)

print(X_test_sid)

# 4.1.2 누락된 값 다루기

# 다른 값으로 대체
from sklearn.impute import SimpleImputer
import numpy as np

X = np.array([[1, 6, 3], [4, 5, 3], [3, 7, 5], [2, 5, None], [8, 5, 1]])
imputer = SimpleImputer(strategy='median') # 중앙값으로 채움
X_imputed = imputer.fit_transform(X)
print(X_imputed)

[[-0.54545455]
 [ 0.27272727]
 [ 1.63636364]
 [-0.90909091]
 [ 0.81818182]]
[[1. 6. 3.]
 [4. 5. 3.]
 [3. 7. 5.]
 [2. 5. 3.]
 [8. 5. 1.]]


In [6]:
# 4.2 문자열 데이트

# 4.2.1 토큰화 
from konlpy.tag import Okt, Kkma
okt = Okt()
okt_result = okt.morphs('여정은 그 자체로 보상')
kkm = Kkma()
kkm_result = kkm.morphs('여정은 그 자체로 보상')






In [8]:
okt = Okt()
okt_result = okt.pos('여정은 가제초로 보상입니다.')

print(okt_result)

[('여정', 'Noun'), ('은', 'Josa'), ('가제', 'Noun'), ('초로', 'Noun'), ('보상', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation')]


In [21]:
# 4.2.2 정규 표현식

import re
sentences = ['텐서플로 출시일은 2015.11.9.입니다',
'텐서플로의 2버전대는 2019.10.1.에 출시합니다',
'사이킷런 0.23 버전은 20.5.12.에 출시했습니다.']

pattern = re.compile('\d{2,4}\.\d{1,2}\.\d{1,2}\.')

for sentence in sentences:
    print(sentence)
    match = pattern.search(sentence)

    print(match.group())

텐서플로 출시일은 2015.11.9.입니다
2015.11.9.
텐서플로의 2버전대는 2019.10.1.에 출시합니다
2019.10.1.
사이킷런 0.23 버전은 20.5.12.에 출시했습니다.
20.5.12.


In [ ]:
# 4.3 이미지 데이터
## 이미지 처리에 가장 인기있는 파이썬 라이브러리 OpenCV

