In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets
from tensorflow.keras.models import Sequential
from tensorflow.keras import Input
from tensorflow.keras.layers import Dense

boston_housing = datasets.boston_housing
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

model = Sequential()
model.add(Input(shape=(13,)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=1))
model.summary()

model.compile(optimizer='RMSprop', loss='mse', metrics=['mae', 'mse'])
model.fit(x_train, y_train, validation_split=0.2, epochs=5)

loss, mae, mse = model.evaluate(x_test, y_test, verbose=2)

predictons = model.predict(x_test)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 64)                896       
                                                                 
 dense_13 (Dense)            (None, 64)                4160      
                                                                 
 dense_14 (Dense)            (None, 1)                 65        
                                                                 
Total params: 5,121
Trainable params: 5,121
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
11/11 [==============================] - 0s 14ms/step - loss: 381.1111 - mae: 12.3408 - mse: 381.1111 - val_loss: 86.6532 - val_mae: 7.3321 - val_mse: 86.6532
Epoch 2/5
11/11 [==============================] - 0s 4ms/step - loss: 80.2226 - mae: 6.5075 - mse: 80.2226 - val_loss: 78.9023 - val_mae: 5.9257 -

In [8]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

mnist = datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255, x_test / 255

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_17 (Dense)            (None, 128)               100480    
                                                                 
 dense_18 (Dense)            (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [3]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers.experimental.preprocessing import Normalization
from tensorflow.keras.layers.experimental.preprocessing import StringLookup
from tensorflow.keras.layers.experimental.preprocessing import CategoryEncoding

file_url = 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv'
heart_df=pd.read_csv(file_url)

df = heart_df['thal'].to_numpy()
layer1 = StringLookup() # 문자값을 정수 인덱스로 매핑
layer1.adapt(df)
print(layer1)
layer2 = CategoryEncoding(num_tokens=6, output_mode="one_hot") #원 핫 인코딩의 형태로 변환
layer2_df = layer2(layer1(df))

print(layer2_df)

tf.Tensor(
[[0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]], shape=(303, 6), dtype=float32)


In [6]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers.experimental.preprocessing import Normalization
from tensorflow.keras.layers.experimental.preprocessing import StringLookup
from tensorflow.keras.layers.experimental.preprocessing import CategoryEncoding

file_url = 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv'
heart_df=pd.read_csv(file_url)

heart_df['age'].value_counts().count()
heart_df['age']

0      63
1      67
2      67
3      37
4      41
       ..
298    52
299    43
300    65
301    48
302    63
Name: age, Length: 303, dtype: int64

In [9]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input

model = Sequential()
model.add(Input(shape=(28, 28)))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='softmax'))


model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 28, 32)            928       
                                                                 
 dense_7 (Dense)             (None, 28, 16)            528       
                                                                 
 dense_8 (Dense)             (None, 28, 10)            170       
                                                                 
Total params: 1,626
Trainable params: 1,626
Non-trainable params: 0
_________________________________________________________________


In [16]:
from tensorflow.keras import Model
from tensorflow.keras.layers import concatenate
from tensorflow.keras.utils import plot_model
input_image = Input(shape=(784,), name='input_image')
input_csv = Input(shape=(13,), name='input_csv')

x1 = Dense(units=32, activation='relu', name='layer10')(input_image)
x1 = Dense(units=16, activation='relu', name='layer11')(x1)
output_image = Dense(units=10, activation='softmax', name='output_image')(x1)

x2 = Dense(units=16, activation='relu', name='layer20')(input_csv)
x2 = Dense(units=8, activation='relu', name='layer21')(x2)
output_csv = Dense(units=1, activation='sigmoid', name='output_csv')(x2)

x3 = concatenate([output_image, output_csv], name='layer30')
output = Dense(8, activation='sigmoid', name='output')(x3)

model=Model([input_image, input_csv], output, name='MODEL:Multiple Inputs')
model.summary()
plot_model(model, "mnist-model.png", show_shapes=True)

Model: "MODEL:Multiple Inputs"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_image (InputLayer)       [(None, 784)]        0           []                               
                                                                                                  
 input_csv (InputLayer)         [(None, 13)]         0           []                               
                                                                                                  
 layer10 (Dense)                (None, 32)           25120       ['input_image[0][0]']            
                                                                                                  
 layer20 (Dense)                (None, 16)           224         ['input_csv[0][0]']              
                                                                              

In [22]:
from tensorflow.keras import Model

class MnistModel(tf.keras.model):
    def __init__(self):
        super(MnistModel, self).__init__()
        self.layers1 = Dense(32, activation='relu')
        self.layers2 = Dense(16, activation='relu')        
        self.layers3 = Dense(10, activation='softmax')
        
    def call(self, x):
        x = self.layers1(x)
        x = self.layers2(x)
        x = self.layers3(x)
        return x
    
model = MnistModel()
model(Input(shape=(784,)))
model.summary()

AttributeError: module 'tensorflow.keras' has no attribute 'model'

In [24]:
from tensorflow.keras import datasets
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

mnist = datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255, x_test/255

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(10, activation='softmax'),
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(x=x_train, y=y_train, epochs=1)

1875/1875 [==============================] - 2s 1ms/step - loss: 0.3741 - accuracy: 0.8925


In [25]:
from tensorflow.keras.callbacks import EarlyStopping

callback_EarlyStopping = EarlyStopping(monitor='val_loss', patience=5, verbose=1)

history = model.fit(x_train, y_train, validation_split=0.2, epochs=20, batch_size=1, callbacks=callback_EarlyStopping, verbose=1)


Epoch 1/20
48000/48000 [==============================] - 50s 1ms/step - loss: 0.2391 - accuracy: 0.9308 - val_loss: 0.1974 - val_accuracy: 0.9417
Epoch 2/20
48000/48000 [==============================] - 62s 1ms/step - loss: 0.1730 - accuracy: 0.9496 - val_loss: 0.1637 - val_accuracy: 0.9536
Epoch 3/20
48000/48000 [==============================] - 62s 1ms/step - loss: 0.1484 - accuracy: 0.9572 - val_loss: 0.1660 - val_accuracy: 0.9547
Epoch 4/20
48000/48000 [==============================] - 56s 1ms/step - loss: 0.1359 - accuracy: 0.9622 - val_loss: 0.1624 - val_accuracy: 0.9568
Epoch 5/20
48000/48000 [==============================] - 50s 1ms/step - loss: 0.1265 - accuracy: 0.9634 - val_loss: 0.1576 - val_accuracy: 0.9598
Epoch 6/20
48000/48000 [==============================] - 59s 1ms/step - loss: 0.1206 - accuracy: 0.9663 - val_loss: 0.1709 - val_accuracy: 0.9561
Epoch 7/20
48000/48000 [==============================] - 57s 1ms/step - loss: 0.1124 - accuracy: 0.9676 - val_loss: 0

In [29]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import tensorflow_datasets as tfds

ds, info = tfds.load('titanic', split='train', with_info=True)
print(ds)

ModuleNotFoundError: No module named 'tensorflow_datasets'

In [31]:
import tensorflow as tf
from tensorflow.keras import activations

x = tf.constant([-9, -6, -3, 0, 3, 6, 9])
activations.relu(x).numpy()


array([0, 0, 0, 0, 3, 6, 9])

      Unnamed: 0  Weight (kg)  Standing Height (cm)  BMI(kg/m**2)
0              0         97.1                 160.2          37.8
1              1         98.8                 182.3          29.7
2              2         74.3                 184.2          21.9
3              3        103.7                 185.3          30.2
4              4         83.3                 177.1          26.6
...          ...          ...                   ...           ...
8383        8383         94.3                 178.8          29.5
8384        8384         82.8                 147.8          37.9
8385        8385        108.8                 168.7          38.2
8386        8386         79.5                 176.4          25.5
8387        8387         59.7                 167.5          21.3

[8388 rows x 4 columns]
